### ISSUE TITLE
Calibre doesn't open due to missing shared object file

### ISSUE THREAD

**Issue by diazbastian** [flathub/com.calibre_ebook.calibre#225] opened 2024-08-24 04:24 UTC
Hi. I recently updated Calibre flatpak and when I tried to open it nothing happened. When I ran it from the terminal using `flatpak run com.calibre_ebook.calibre` I got the following error:

```
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 47, in <module>
  File "site.py", line 43, in main
  File "calibre/gui_launch.py", line 74, in calibre
  File "calibre/gui2/main.py", line 548, in main
  File "calibre/gui2/main.py", line 560, in run_main
  File "calibre/gui2/main.py", line 398, in run_gui
  File "calibre/gui2/main.py", line 408, in run_gui_
  File "bypy-importer.py", line 279, in exec_module
  File "calibre/gui2/ui.py", line 50, in <module>
  File "bypy-importer.py", line 279, in exec_module
  File "calibre/gui2/init.py", line 37, in <module>
  File "bypy-importer.py", line 279, in exec_module
  File "calibre/gui2/library/alternate_views.py", line 18, in <module>
  File "bypy-importer.py", line 279, in exec_module
  File "PIL/Image.py", line 82, in <module>
  File "bypy-importer.py", line 127, in create_module
ImportError: libdeflate.so.0: cannot open shared object file: No such file or directory
```

OS: Fedora Workstation 40 (GNOME 46 Wayland)
Calibre version 7.17.0 (stable branch) commit b104ce4b98130ad6f5c2a93ed3074f5643a1e4403e29a411a90a152f516813cd
Runtime: org.freedesktop.Platform/x86_64/23.08

**Comment by mihailim** [comment] 2024-08-24 07:16
Confirming, same behavior on Ubuntu 24.04 (unsurprisingly, since Flatpak :D)
None of the various packaged binaries from `/app/bin` seem to work since they all attempt to load that library.

**Comment by rag2** [comment] 2024-08-24 10:17
Also confirming same behaviour in Ubuntu 18.04 ESM (don't ask why!)
Thanks to @mihailim for the fix. Much appreciated. I confirm that the fix above works, in this case with the addition of a sudo prefix.

**Comment by ghisvail** [comment] 2024-08-24 10:44
Looks like there has been a change in the dependency chain since version 7.17.0. It was working fine before on 7.16.0

Pinging @kovidgoyal to check whether the solution is expected to be on our end, or upstream.

**Comment by ghisvail** [comment] 2024-08-24 10:46
Meanwhile, users should temporarily revert to the previous Flatpak revision using [this set of instructions](https://github.com/flathub/com.calibre_ebook.calibre/issues/225#issuecomment-2308162405).

**Comment by Erick555** [comment] 2024-08-24 12:15
yeah, the problem is `libtiff.so.6` links to `libdeflate.so.0` but the latter isn't included in calibre tarball which makes calibre not self-contained anymore.

**Comment by igor2x** [comment] 2024-08-24 14:05
I have reverted back to previous version like described in second post and Calibre works again.

Is there some reason manifest file com.calibre_ebook.calibre.yaml isn't reverted back to previous working commit and flatpak created with previous working version. We can't expect all users are tech savvy and working with terminal.

**Comment by ghisvail** [comment] 2024-08-24 14:07
@igor2x because if you dared to look at the list of PRs, you'd have seen someone actually provided a fix for it...

**Comment by ghisvail** [comment] 2024-08-24 14:17
Fixed by @Erick555, reported upstream [here](https://bugs.launchpad.net/calibre/+bug/2077794).

**Closed by ghisvail** 2024-08-24 14:17 UTC
Labels: bug, upstream

**Comment by mihailim** [comment] 2024-08-25 17:27
Fixed upstream as well, the next release will ship the libdeflate .so. `4eec555` will probably need to be reverted for that build.

**Comment by Erick555** [comment] 2024-08-25 20:08
It should be reverted although it's not urgent as not reverting is harmless for users - flatpak will have just two copies of same library.
