### ISSUE TITLE
Broken theme

### ISSUE THREAD

**Issue by garrett** [flathub/com.calibre_ebook.calibre#2] opened 2018-09-12 08:24 UTC
Wow! Firstly: Thanks for packaging Calibre in Flathub!

It's not really usable at the moment, due to it using a weird and broken theme.

![calibre](https://user-images.githubusercontent.com/10246/45411640-03718400-b675-11e8-8568-5ce7445fbcf7.png)

It's ugly, doesn't look like the system theme (in my case, GNOME with stock Adwaita), and most importantly, the scrollbars are completely black, so they're 100% unusable.

This is probably a side effect of upstream hacking out support for themes on Linux by default, a while back. See https://calibre-ebook.com/new-in/twelve, specifically the "Backwards incompatibilities" section:

> On Linux calibre can no longer use the system Qt theme/style plugins as they cause hangs/crashes on some systems. This means calibre might look a little different from other applications on your system. You can force the use of the system theme by setting the environment variable CALIBRE_USE_SYSTEM_THEME, but do so at your own risk.

I've been using native Calibre in Fedora with the stock GNOME theme (Adwaita) for a long while now and it works perfectly. I've never had a single hang or crash. 

To enable it, you basically need to have `CALIBRE_USE_SYSTEM_THEME=true` as an environmental variable. Of course, because Calibre is running from a Flatpak, the system variable isn't reflected within, so it would need to be added inside of the Flatpak itself.

**Comment by garrett** [comment] 2018-09-12 08:27
Additionally, the menus (when you click on the triangles) are completely blank. Some dialogs also have missing text and broken widgets too.

These issues could all be theme related.

**Comment by ghisvail** [comment] 2018-09-12 08:39
> It's not really usable at the moment, due to it using a weird and broken theme.

It's been quite usable for me until now. I appreciate the encouraging opening statement.

> It's ugly, doesn't look like the system theme (in my case, GNOME with stock Adwaita), and most importantly, the scrollbars are completely black, so they're 100% unusable.

That's certainly not my experience:

![capture d ecran de 2018-09-12 10-32-15](https://user-images.githubusercontent.com/1964655/45412648-7da30800-b677-11e8-8870-913a70a72c82.png)

> I've been using native Calibre in Fedora with the stock GNOME theme (Adwaita) for a long while now and it works perfectly. I've never had a single hang or crash.

Note that I am using Debian (stable and testing) instead of Fedora. On both, the application looks fine as the screenshot above demonstrates.

> To enable it, you basically need to have CALIBRE_USE_SYSTEM_THEME=true as an environmental variable. Of course, because Calibre is running from a Flatpak, the system variable isn't reflected within, so it would need to be added inside of the Flatpak itself.

I'd need to understand the origin of the differences between your experience and mine before jumping to a solution.

**Comment by garrett** [comment] 2018-09-12 09:26
Oddly, things are working on a fresh Fedora 28 Silverblue install. I wonder what the difference is. 

Perhaps it's due to re-using my existing library, which I assume also pulls in previous settings?

(I'll look more into this later.)

**Comment by ghisvail** [comment] 2018-09-16 20:55
I'll close this issue as it contains a lot of noise already and is not reproducible on my end.

Please consider opening a new one in the future when the problem is captured and understood.

Thanks.

**Closed by ghisvail** 2018-09-16 20:55 UTC
