### ISSUE TITLE
Calibre is missing on Flathub.org?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.calibre_ebook.calibre#1] opened 2018-09-10 20:21 UTC
The Calibre page is missing on the Flathub website and the Flatpak is also missing in GNOME Software. It looks like that there is some issue with the AppStream metadata.
![captura de tela de 2018-09-07 19-53-55](https://user-images.githubusercontent.com/26097419/45246460-ca818a00-b2d7-11e8-8c03-984b7d9e9e33.png)

**Comment by Erick555** [comment] 2018-09-10 23:14
There are some warnings but I don't know if this is the cause:

```
$ appstream-util validate-relax com.calibre_ebook.calibre.appdata.xml
com.calibre_ebook.calibre.appdata.xml: FAILED:
• attribute-invalid     : <screenshot> width too small [https://lh6.ggpht.com/_lG58t3XWd3c/SwsfKwvvC0I/AAAAAAAAABo/dnQgVrEwinw/s144/convert.png] minimum is 300px
• attribute-invalid     : <screenshot> height too small [https://lh6.ggpht.com/_lG58t3XWd3c/SwsfKwvvC0I/AAAAAAAAABo/dnQgVrEwinw/s144/convert.png] minimum is 150px
• attribute-invalid     : <screenshot> width too small [https://lh5.ggpht.com/_lG58t3XWd3c/SwtEQXhUwVI/AAAAAAAAAB0/AO5OuiC0Cdw/s144/viewer.png] minimum is 300px
• attribute-invalid     : <screenshot> height too small [https://lh5.ggpht.com/_lG58t3XWd3c/SwtEQXhUwVI/AAAAAAAAAB0/AO5OuiC0Cdw/s144/viewer.png] minimum is 150px
• attribute-invalid     : <screenshot> width too small [https://lh6.googleusercontent.com/_lG58t3XWd3c/TcN0Bg4AYEI/AAAAAAAAAEs/E9oa4zanNqM/s144/cs_top.jpeg] minimum is 300px
• attribute-invalid     : <screenshot> height too small [https://lh6.googleusercontent.com/_lG58t3XWd3c/TcN0Bg4AYEI/AAAAAAAAAEs/E9oa4zanNqM/s144/cs_top.jpeg] minimum is 150px
• attribute-invalid     : <screenshot> width too small [https://lh3.googleusercontent.com/_lG58t3XWd3c/TcN0Bpytj3I/AAAAAAAAAEw/VAfVlHr8L3U/s144/cs_list.jpeg] minimum is 300px
• attribute-invalid     : <screenshot> height too small [https://lh3.googleusercontent.com/_lG58t3XWd3c/TcN0Bpytj3I/AAAAAAAAAEw/VAfVlHr8L3U/s144/cs_list.jpeg] minimum is 150px
• attribute-invalid     : <screenshot> width too small [https://lh5.ggpht.com/_lG58t3XWd3c/SwtE6JlJbgI/AAAAAAAAACA/bJ1m3pH8dLA/s144/stanza_and_calibre.png] minimum is 300px
• attribute-invalid     : <screenshot> height too small [https://lh5.ggpht.com/_lG58t3XWd3c/SwtE6JlJbgI/AAAAAAAAACA/bJ1m3pH8dLA/s144/stanza_and_calibre.png] minimum is 150px
Validation of files failed
```

**Comment by ghisvail** [comment] 2018-09-11 06:15
@LeandroStanger, thank you for reporting this issue.

@Erick555, thank you for providing further insights. I have removed the offending screenshots in the following [commit](820a999dbe20bd3c48198242184234359375cf11). Let's see whether it solves the discovery problem.

**Comment by ghisvail** [comment] 2018-09-11 06:50
I also fixed the project license identifier. Not sure what else could cause this.

**Comment by Erick555** [comment] 2018-09-11 10:40
I can find it on KDE Discover but not on [flathub.org](https://flathub.org/apps/search/calibre).

**Comment by ghisvail** [comment] 2018-09-11 10:44
Could be that the job responsible for building the flathub catalog has not kicked in yet.

**Comment by Erick555** [comment] 2018-09-11 17:41
No idea. You have to ask flatpak devs.

**Comment by Erick555** [comment] 2018-09-11 18:39
It's in https://flathub.org/apps/details/com.calibre_ebook.calibre !

**Comment by ghisvail** [comment] 2018-09-11 18:41
I guess my last commit (adding a `launchable` entry to the appdata) was the fix.

I am closing the issue then. Thanks for your help @Erick555.

**Comment by LeandroStanger** [comment] 2018-09-11 20:19
@ghisvail The icon is missing
![captura de tela de 2018-09-11 17-17-21](https://user-images.githubusercontent.com/26097419/45385261-acbd6900-b5e6-11e8-928e-8258179b6e1c.png)

**Comment by Erick555** [comment] 2018-09-11 21:15
@ghisvail I think you have to add icons in [appdata](https://github.com/flathub/com.calibre_ebook.calibre/blob/master/com.calibre_ebook.calibre.appdata.xml), example https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.appdata.xml#L36

**Comment by jgarciao** [comment] 2018-09-12 09:47
The icons are declared in the appstream file  (/var/lib/flatpak/appstream/flathub/x86_64/active)

```
<icon height="128" width="128" type="cached">com.calibre_ebook.calibre.gui.png</icon>
<icon height="64" width="64" type="cached">com.calibre_ebook.calibre.gui.png</icon>
```
But they are not in the web server, so they are not shown in the flathub webpage
https://flathub.org/repo/appstream/x86_64/icons/128x128/com.calibre_ebook.calibre.gui.png

Maybe the problem  that the icon name is com.calibre_ebook.calibre.gui.png  (note the "gui" part), instead of com.calibre_ebook.calibre.png)

Another problem could be that [the build file](https://github.com/flathub/com.calibre_ebook.calibre/commit/d5b3757d56f10be36a71cb1d07c2763e58bbcae7) copies the 256x256 icon but not the required 64x64 and 128x128

**Comment by Erick555** [comment] 2018-09-12 11:30
Why do you create this "gui" suffix alongside non-gui? It seems redundant to me. Doesn't calibre provide other icon sizes than 256x256?

**Comment by ghisvail** [comment] 2018-09-12 14:26
> Why do you create this "gui" suffix?

It makes `com.calibre_ebook.calibre` a namespace for the individual applications, i.e. the GUI, the editor, the viewer and the LRF viewer. Same logic as for `LibreOffice` with Writer, Calc, Draw, etc...

**Comment by ghisvail** [comment] 2018-09-12 14:27
> EDIT: I checked that it provides various icons sizes when building from source but not in prebuild archive. Maybe you can try to use "copy-to-library.png" or "vl.png" for 128x128 icon size.

I might as well just embed the necessary icons to the flatpak repository at this point?

**Comment by Erick555** [comment] 2018-09-12 19:56
I would keep main app as `com.calibre_ebook.calibre` without gui suffix (for me it implies there is non-gui version too which isn't the case) and use suffixes only for helper apps like editor and viewer but that's just my preference which you can ignore.

I agree that pushing icons directly to flathub repo may be the best choice here.

**Comment by nedrichards** [comment] 2018-09-13 09:40
To be correctly attributed by software stores etc. all the exports have to match the name. So if the app-id is com.calibre_ebook.calibre then you need something with com.calibre_ebook.calibre.png otherwise you're going to have issues.

**Comment by ghisvail** [comment] 2018-09-13 09:43
This particular issue (calibre not appearing in flathub) is closed.

Discussions related to icon problems should be followed on #4.

**Closed by ghisvail** 2018-09-13 09:43 UTC
