### ISSUE TITLE
Calibre 5.2.0 fails to init due to wrong permissions on runtime directory

### ISSUE THREAD

**Issue by shiriru** [flathub/com.calibre_ebook.calibre#50] opened 2020-10-07 10:15 UTC
Calibre fails to initialize, reporting following output:
```sh
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=calibre --file-forwarding com.calibre_ebook.calibre 
> QStandardPaths: wrong permissions on runtime directory /run/user/1000, 7755 instead of 7700
```
Calibre version info:
```sh
Name                              Application ID                           Version    Branch  Installation
Calibre                           com.calibre_ebook.calibre                5.2.0      stable  user
```
System environment:
`Linux 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Any solutions and suggestions how to solve this are greatly appreciated!
10x

**Comment by Erick555** [comment] 2020-10-07 12:33
Duplicate of https://github.com/flathub/com.calibre_ebook.calibre/issues/39 see solution in last comment.

**Comment by Erick555** [comment] 2020-10-30 18:12
@shiriru this should be fixed in calibre 5.4.1, please test.

**Comment by ghisvail** [comment] 2020-11-27 22:14
@shiriru could you please update, test and report whether you are still experiencing this issue. It should be fixed.

**Comment by ghisvail** [comment] 2021-01-23 11:25
This issue is supposedly fixed since several releases ago.

**Closed by ghisvail** 2021-01-23 11:25 UTC
