### ISSUE TITLE
Installing calibre using flatpack does not import either my library or my settings

### ISSUE THREAD

**Issue by anaselli** [flathub/com.calibre_ebook.calibre#39] opened 2020-06-14 10:14 UTC
I'm using Mageia Linux and official calibre is still 3.x that now has some problems with my Kobo device, i tried installing new version using flatpack locally:

```
Name                                                      Application ID                                     Version                  Branch          Installation
Calibre                                                   com.calibre_ebook.calibre                          4.18.0                   stable          user

```
It started asking for library path where it founds the guide, but no other books that i had in my previous version (and still have there).

Moreover pressing the help button produces no output running from console it prints:

```
QStandardPaths: wrong permissions on runtime directory /run/user/1001, 7755 instead of 7700
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia ?org.freedesktop.portal.OpenURI? inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop
```
Similar error if i try to open configuration directory from Miscellaneus settings:

```
QStandardPaths: wrong permissions on runtime directory /run/user/1001, 7755 instead of 7700
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia ?org.freedesktop.portal.OpenURI? inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop
```
Apologize if something is italian, but i was not able to run it in English

**Comment by Erick555** [comment] 2020-06-15 18:18
The /run/user/xxx permissions issue is related to https://github.com/containers/bubblewrap/issues/346 but it seems unlikely to be fixed soon. I have patched qt on my host and it works there.

**Comment by lineber** [comment] 2020-09-30 07:05
I have a similar issue. I am not able to add a book from any directory. I get a similar error message:

```
$ flatpak run com.calibre_ebook.calibre
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 7755 instead of 7700
```
> I have patched qt on my host and it works there.

I don't understand what needs to be done to get it to work.

**Comment by Erick555** [comment] 2020-10-04 13:41
In order to make it work with current calibre flatpak (this will also fix all other flatpaks that bundle their own qt)

1. Rebuild `qt5-base` package (this is how Arch Linux name it, other distros may name it differently) with [following patch](https://invent.kde.org/packaging/flatpak-kde-runtime/-/raw/qt5.15lts/patch/qtbase-revert-correct-handling-for-xdg-runtime-dir.patch) included. You have to repeat it everytime your distro updates this package. Unfortunately kde developers [refused to fix](https://github.com/containers/bubblewrap/issues/346#issuecomment-593232683) this issue upstream.
2. If you have `xdg-desktop-portal` version **1.8.0 or higher**, you need to rebuild it with [following patch](https://github.com/flatpak/xdg-desktop-portal/commit/7f11163236c02ef7ad0f3b48c705ad893c2b9f9b.patch) **reverted**. This one will be no longer needed when [proper fix lands in qt](https://codereview.qt-project.org/c/qt/qtbase/+/315094).

**Comment by Erick555** [comment] 2020-10-30 18:13
@anaselli @lineber  this should be fixed in calibre 5.4.1, please test.

**Comment by anaselli** [comment] 2020-10-30 20:12
@Erick555 what should work exactly? I can't see my calibre library since it is into ~/Documents/Calibre Library (Italian translation here) 
I tried the welcome wizard but i can't change the path (the change button does nothing)
I also tried choose a calibre library but again i can't change the path with button
At that point i added it by keyboard and had my library back

**Comment by Erick555** [comment] 2020-10-30 21:47
The errors messages you posted should be gone. If you have **xdg-desktop-portal 1.8.0 or higher** then you have to wait until calibre 5.5 to fix opening help/config, etc.

**Comment by anaselli** [comment] 2020-10-31 09:40
Ah ok, the error indeed is gone :) but help button does nothing though. Should we open or reference another issue for this related problems?

**Comment by Erick555** [comment] 2020-10-31 12:29
@anaselli it depends on what version of xdg-desktop-portal do you have installed. If it's below 1.8.0 then please open new issue otherwise please wait for calibre 5.5.

**Comment by anaselli** [comment] 2020-10-31 17:26
rpm -qa | grep xdg-desktop-portal
xdg-desktop-portal-1.4.2-1.mga7

**Comment by Erick555** [comment] 2020-10-31 17:45
Then this may be unrelated issue. can you confirm if adding books and opening directories work?

**Comment by anaselli** [comment] 2020-10-31 17:55
No, it seems not to work here

**Comment by Erick555** [comment] 2020-10-31 18:22
I don't know then but I tested everything you reported including help and it worked for me. Do you have similar issues with other flatpaks?

**Comment by anaselli** [comment] 2020-10-31 19:35
don't know, i have only spotify and works for what i can say. Maybe i missed some requirements? I'll try to install the official one and see...

**Comment by anaselli** [comment] 2020-10-31 19:39
nope official calibre 3.x works the flatpack one no.

**Comment by Erick555** [comment] 2020-10-31 20:19
I meant if in other flatpaks you can open files/folders from your system. You may try running in background `G_MESSAGES_DEBUG=all /usr/lib/xdg-desktop-portal --replace --verbose` then and paste here what it shows while you try opening something in calibre

**Comment by anaselli** [comment] 2020-10-31 21:55
xdg-desktop-portal is under /usr/libexec here. The only output it prints is when i run your command, nothing happens using calibre, should i run it in a special way?

Below all the command output:


```
G_MESSAGES_DEBUG=all /usr/libexec/xdg-desktop-portal --replace --verbose
(/usr/libexec/xdg-desktop-portal:32318): GLib-GIO-DEBUG: 22:52:05.533: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
(/usr/libexec/xdg-desktop-portal:32318): GLib-GIO-DEBUG: 22:52:05.537: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(/usr/libexec/xdg-desktop-portal:32318): GLib-GIO-DEBUG: 22:52:05.539: Failed to initialize networkmanager (GNetworkMonitorNM) for gio-network-monitor: NetworkManager non è in esecuzione
(/usr/libexec/xdg-desktop-portal:32318): GLib-GIO-DEBUG: 22:52:05.539: _g_io_module_get_default: Found default implementation netlink (GNetworkMonitorNetlink) for ‘gio-network-monitor’
XDP: providing portal org.freedesktop.portal.NetworkMonitor
(/usr/libexec/xdg-desktop-portal:32318): GLib-GIO-DEBUG: 22:52:05.541: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.541: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.541: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.541: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.541: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.541: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.541: unwatch_fast: "/system/proxy/" (active: 0, establishing: 1)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.541: unwatch_fast: "/system/proxy/http/" (active: 0, establishing: 1)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.541: unwatch_fast: "/system/proxy/https/" (active: 0, establishing: 1)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.541: unwatch_fast: "/system/proxy/ftp/" (active: 0, establishing: 1)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.541: unwatch_fast: "/system/proxy/socks/" (active: 0, establishing: 1)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.542: watch_established: "/system/proxy/" (establishing: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.542: watch_established: "/system/proxy/http/" (establishing: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.542: watch_established: "/system/proxy/https/" (establishing: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.542: watch_established: "/system/proxy/ftp/" (establishing: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.542: watch_established: "/system/proxy/socks/" (establishing: 0)
(/usr/libexec/xdg-desktop-portal:32318): GLib-GIO-DEBUG: 22:52:05.544: _g_io_module_get_default: Found default implementation libproxy (GLibproxyResolver) for ‘gio-proxy-resolver’
XDP: providing portal org.freedesktop.portal.ProxyResolver
XDP: providing portal org.freedesktop.portal.Trash
XDP: providing portal org.freedesktop.portal.GameMode
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.545: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
XDP: org.gnome.settings-daemon.peripherals.mouse schema not found
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.545: watch_fast: "/org/gnome/desktop/sound/" (establishing: 0, active: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.545: watch_fast: "/org/gnome/desktop/privacy/" (establishing: 0, active: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.545: watch_fast: "/org/gnome/desktop/wm/preferences/" (establishing: 0, active: 0)
XDP: org.gnome.settings-daemon.plugins.xsettings schema not found
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.545: watch_fast: "/org/gnome/desktop/a11y/" (establishing: 0, active: 0)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.545: watch_established: "/org/gnome/desktop/interface/" (establishing: 1)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.545: watch_established: "/org/gnome/desktop/sound/" (establishing: 1)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.545: watch_established: "/org/gnome/desktop/privacy/" (establishing: 1)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.545: watch_established: "/org/gnome/desktop/wm/preferences/" (establishing: 1)
(/usr/libexec/xdg-desktop-portal:32318): dconf-DEBUG: 22:52:05.545: watch_established: "/org/gnome/desktop/a11y/" (establishing: 1)
XDP: Monitoring /etc/fonts/fonts.conf
XDP: Monitoring /etc/fonts/conf.d
XDP: Monitoring /etc/fonts/conf.d/00-cache.conf
XDP: Monitoring /etc/fonts/conf.d/10-hinting-slight.conf
XDP: Monitoring /etc/fonts/conf.d/10-scale-bitmap-fonts.conf
XDP: Monitoring /etc/fonts/conf.d/20-mdv-disable-antialias.conf
XDP: Monitoring /etc/fonts/conf.d/20-unhint-small-dejavu-sans-mono.conf
XDP: Monitoring /etc/fonts/conf.d/20-unhint-small-dejavu-sans.conf
XDP: Monitoring /etc/fonts/conf.d/20-unhint-small-dejavu-serif.conf
XDP: Monitoring /etc/fonts/conf.d/20-unhint-small-vera.conf
XDP: Monitoring /etc/fonts/conf.d/25-no-bitmap-fedora.conf
XDP: Monitoring /etc/fonts/conf.d/25-unhint-nonlatin.conf
XDP: Monitoring /etc/fonts/conf.d/26-mdv-no-embeddedbitmap.conf
XDP: Monitoring /etc/fonts/conf.d/30-0-google-crosextra-caladea-fontconfig.conf
XDP: Monitoring /etc/fonts/conf.d/30-0-google-crosextra-carlito-fontconfig.conf
XDP: Monitoring /etc/fonts/conf.d/30-mdv-avoid-bitmap.conf
XDP: Monitoring /etc/fonts/conf.d/30-mdv-urwfonts.conf
XDP: Monitoring /etc/fonts/conf.d/30-metric-aliases.conf
XDP: Monitoring /etc/fonts/conf.d/31-cantarell.conf
XDP: Monitoring /etc/fonts/conf.d/40-nonlatin.conf
XDP: Monitoring /etc/fonts/conf.d/45-generic.conf
XDP: Monitoring /etc/fonts/conf.d/45-latin.conf
XDP: Monitoring /etc/fonts/conf.d/49-sansserif.conf
XDP: Monitoring /etc/fonts/conf.d/50-user.conf
XDP: Monitoring /home/angelo/.config/fontconfig/fonts.conf
XDP: Monitoring /etc/fonts/conf.d/51-local.conf
XDP: Monitoring /etc/fonts/conf.d/57-dejavu-sans-mono.conf
XDP: Monitoring /etc/fonts/conf.d/57-dejavu-sans.conf
XDP: Monitoring /etc/fonts/conf.d/57-dejavu-serif.conf
XDP: Monitoring /etc/fonts/conf.d/59-liberation-mono.conf
XDP: Monitoring /etc/fonts/conf.d/59-liberation-sans.conf
XDP: Monitoring /etc/fonts/conf.d/59-liberation-serif.conf
XDP: Monitoring /etc/fonts/conf.d/60-generic.conf
XDP: Monitoring /etc/fonts/conf.d/60-latin.conf
XDP: Monitoring /etc/fonts/conf.d/61-adobe-source-code-pro.conf
XDP: Monitoring /etc/fonts/conf.d/62-google-crosextra-caladea-fontconfig.conf
XDP: Monitoring /etc/fonts/conf.d/62-google-crosextra-carlito-fontconfig.conf
XDP: Monitoring /etc/fonts/conf.d/65-fonts-persian.conf
XDP: Monitoring /etc/fonts/conf.d/65-nonlatin.conf
XDP: Monitoring /etc/fonts/conf.d/67-gnu-free-mono.conf
XDP: Monitoring /etc/fonts/conf.d/69-unifont.conf
XDP: Monitoring /etc/fonts/conf.d/80-delicious.conf
XDP: Monitoring /etc/fonts/conf.d/90-synthetic.conf
XDP: Monitoring /usr/share/fonts
XDP: Monitoring /usr/share/X11/fonts/Type1
XDP: Monitoring /usr/share/X11/fonts/TTF
XDP: Monitoring /usr/local/share/fonts
XDP: Monitoring /usr/lib/X11/fonts
XDP: Monitoring /opt/ttfonts
XDP: Monitoring /home/angelo/.local/share/fonts
XDP: Monitoring /home/angelo/.fonts
XDP: Monitoring /usr/share/fonts/100dpi
XDP: Monitoring /usr/share/fonts/75dpi
XDP: Monitoring /usr/share/fonts/OTF
XDP: Monitoring /usr/share/fonts/Speedo
XDP: Monitoring /usr/share/fonts/TTF
XDP: Monitoring /usr/share/fonts/Type1
XDP: Monitoring /usr/share/fonts/cantarell
XDP: Monitoring /usr/share/fonts/cyrillic
XDP: Monitoring /usr/share/fonts/default
XDP: Monitoring /usr/share/fonts/encodings
XDP: Monitoring /usr/share/fonts/gnu-free
XDP: Monitoring /usr/share/fonts/google-crosextra-caladea
XDP: Monitoring /usr/share/fonts/google-crosextra-carlito
XDP: Monitoring /usr/share/fonts/mathjax
XDP: Monitoring /usr/share/fonts/misc
XDP: Monitoring /usr/share/fonts/opensymbol
XDP: Monitoring /usr/share/fonts/truetype
XDP: Monitoring /usr/share/fonts/ttf
XDP: Monitoring /usr/share/fonts/OTF/adobe-source-code-pro
XDP: Monitoring /usr/share/fonts/TTF/dejavu
XDP: Monitoring /usr/share/fonts/TTF/liberation
XDP: Monitoring /usr/share/fonts/TTF/unifont
XDP: Monitoring /usr/share/fonts/default/Type1
XDP: Monitoring /usr/share/fonts/default/ghostscript
XDP: Monitoring /usr/share/fonts/encodings/large
XDP: Monitoring /usr/share/fonts/truetype/oxygen
XDP: Monitoring /usr/share/fonts/ttf/decoratives
XDP: Monitoring /usr/share/fonts/ttf/western
XDP: Monitoring /usr/share/fonts/default/Type1/adobestd35
XDP: providing portal org.freedesktop.portal.Settings
XDP: org.freedesktop.portal.Desktop acquired


```

**Comment by Erick555** [comment] 2020-10-31 22:13
It should print new messages when flatpak is started and file actions are used. Do you have `xdg-dsktop-portal-gtk` (or kde) installed as well?

**Comment by Erick555** [comment] 2020-10-31 22:27
I found that people reported flatpak issues on mageia 7 or older so it's possible you won't be able to make it work witohut updatting to mageia 8: https://bugs.mageia.org/show_bug.cgi?id=27126

**Comment by anaselli** [comment] 2020-10-31 23:47
Well 8 is not released yet, so i'll test in cauldron just to be sure it works later though.

**Comment by ghisvail** [comment] 2020-11-27 14:11
Version 5.6 is out. Could you please test and report whether the issue is fixed. Thanks.

**Comment by BoltsJ** [comment] 2020-11-27 20:20
I can open PDFs and folders from the library view now.

**Comment by anaselli** [comment] 2020-11-27 22:41
Confirming that calibre 5.6.0 is still does not work under mageia 7. I haven't found the time to testi in mageia 8 though, sorry

**Comment by ghisvail** [comment] 2020-11-29 10:38
The [mageia bug report](https://bugs.mageia.org/show_bug.cgi?id=27126) mentioned it should be fixed for version 8 onwards.

**Comment by anaselli** [comment] 2020-11-29 15:42
yeah i'm managing to try backporting things but need to see if it is safe enough or have to change too much...

**Comment by ghisvail** [comment] 2021-01-23 11:13
Closing as this bug seems downstream specific and should be fixed by updating dependencies. Please re-open if there is nothing actionable here.

**Closed by ghisvail** 2021-01-23 11:13 UTC
